//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeMockPlugin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeMockPlugin() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockPlugin.Properties.LocalizeMockPlugin", typeof(LocalizeMockPlugin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send a message to my device ähnelt.
        /// </summary>
        internal static string BrewCoffee_GetTaskAction_Send_a_message_to_my_device {
            get {
                return ResourceManager.GetString("BrewCoffee_GetTaskAction_Send_a_message_to_my_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want sugar? ähnelt.
        /// </summary>
        internal static string BrewCoffee_mMessage_Do_you_want_sugar_ {
            get {
                return ResourceManager.GetString("BrewCoffee_mMessage_Do_you_want_sugar_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brew a frappuccino, composition:  ähnelt.
        /// </summary>
        internal static string BrewFrappuccino_GetTaskAction_Brew_a_frappuccino__composition__ {
            get {
                return ResourceManager.GetString("BrewFrappuccino_GetTaskAction_Brew_a_frappuccino__composition__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coffee ähnelt.
        /// </summary>
        internal static string CoffeeCategory_Name_Coffee {
            get {
                return ResourceManager.GetString("CoffeeCategory_Name_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cream: {0}; MuchIce: {1}; Decaffeinated: {2}, Size: {3} mL ähnelt.
        /// </summary>
        internal static string CompositionData_ToString_Cream___0___MuchIce___1___Decaffeinated___2___Size___3__mL {
            get {
                return ResourceManager.GetString("CompositionData_ToString_Cream___0___MuchIce___1___Decaffeinated___2___Size___3__" +
                        "mL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The coffee machine&apos;s heater failed. ähnelt.
        /// </summary>
        internal static string PretendCoffeeMachineIsBroken_Execute_The_coffee_machine_s_heater_failed_ {
            get {
                return ResourceManager.GetString("PretendCoffeeMachineIsBroken_Execute_The_coffee_machine_s_heater_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Will make the device abort the schedule after a few seconds. ähnelt.
        /// </summary>
        internal static string PretendCoffeeMachineIsBroken_GetTaskAction_Will_make_the_device_abort_the_schedule_after_a_few_seconds_ {
            get {
                return ResourceManager.GetString("PretendCoffeeMachineIsBroken_GetTaskAction_Will_make_the_device_abort_the_schedul" +
                        "e_after_a_few_seconds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Showing a messagebox with the text &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string ShowingAMessageboxWithTheTextX0 {
            get {
                return ResourceManager.GetString("ShowingAMessageboxWithTheTextX0", resourceCulture);
            }
        }
    }
}
