//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeMockPlugin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeMockPlugin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockPlugin.Properties.LocalizeMockPlugin", typeof(LocalizeMockPlugin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to my device.
        /// </summary>
        internal static string BrewCoffee_GetTaskAction_Send_a_message_to_my_device {
            get {
                return ResourceManager.GetString("BrewCoffee_GetTaskAction_Send_a_message_to_my_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want sugar?.
        /// </summary>
        internal static string BrewCoffee_mMessage_Do_you_want_sugar_ {
            get {
                return ResourceManager.GetString("BrewCoffee_mMessage_Do_you_want_sugar_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brew a frappuccino, composition: .
        /// </summary>
        internal static string BrewFrappuccino_GetTaskAction_Brew_a_frappuccino__composition__ {
            get {
                return ResourceManager.GetString("BrewFrappuccino_GetTaskAction_Brew_a_frappuccino__composition__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        internal static string CoffeeCategory_Name_Coffee {
            get {
                return ResourceManager.GetString("CoffeeCategory_Name_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cream: {0}; MuchIce: {1}; Decaffeinated: {2}, Size: {3} mL.
        /// </summary>
        internal static string CompositionData_ToString_Cream___0___MuchIce___1___Decaffeinated___2___Size___3__mL {
            get {
                return ResourceManager.GetString("CompositionData_ToString_Cream___0___MuchIce___1___Decaffeinated___2___Size___3__" +
                        "mL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle through.
        /// </summary>
        internal static string CreamTypeColumn_ColumnHeaderMenu_Cycle_through {
            get {
                return ResourceManager.GetString("CreamTypeColumn_ColumnHeaderMenu_Cycle_through", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill down.
        /// </summary>
        internal static string CreamTypeColumn_ColumnHeaderMenu_Fill_down {
            get {
                return ResourceManager.GetString("CreamTypeColumn_ColumnHeaderMenu_Fill_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DateColumn_ColumnHeaderMenu_Daily {
            get {
                return ResourceManager.GetString("DateColumn_ColumnHeaderMenu_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill down.
        /// </summary>
        internal static string DateColumn_ColumnHeaderMenu_Fill_down {
            get {
                return ResourceManager.GetString("DateColumn_ColumnHeaderMenu_Fill_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string DateColumn_ColumnHeaderMenu_Monthly {
            get {
                return ResourceManager.GetString("DateColumn_ColumnHeaderMenu_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string DateColumn_ColumnHeaderMenu_Weekly {
            get {
                return ResourceManager.GetString("DateColumn_ColumnHeaderMenu_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateColumn_VisibleName_Date {
            get {
                return ResourceManager.GetString("DateColumn_VisibleName_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coffee machine&apos;s heater failed..
        /// </summary>
        internal static string PretendCoffeeMachineIsBroken_Execute_The_coffee_machine_s_heater_failed_ {
            get {
                return ResourceManager.GetString("PretendCoffeeMachineIsBroken_Execute_The_coffee_machine_s_heater_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will make the device abort the schedule after a few seconds. SoftStop is {0}..
        /// </summary>
        internal static string PretendCoffeeMachineIsBroken_GetTaskAction_Will_make_the_device_abort_the_schedule_after_a_few_seconds_ {
            get {
                return ResourceManager.GetString("PretendCoffeeMachineIsBroken_GetTaskAction_Will_make_the_device_abort_the_schedul" +
                        "e_after_a_few_seconds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing a messagebox with the text &quot;{0}&quot;.
        /// </summary>
        internal static string ShowingAMessageboxWithTheTextX0 {
            get {
                return ResourceManager.GetString("ShowingAMessageboxWithTheTextX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status text at {0}
        ///for device {1}.
        /// </summary>
        internal static string StatusViewControl_timer1_Tick_ {
            get {
                return ResourceManager.GetString("StatusViewControl_timer1_Tick_", resourceCulture);
            }
        }
    }
}
